import '@storybook/addon-ondevice-actions/register'
import '@storybook/addon-ondevice-backgrounds/register'
import '@storybook/addon-ondevice-notes/register'
// import '@storybook/addon-ondevice-controls/register'
import '@storybook/addon-ondevice-knobs/register'
